### PR TITLE
Added option to choose size of artwork limit

### PR DESCRIPTION
**Pull request by freakyfr1day**
Added a slider in the settings to choose how many of each artwork type to allow.

Default is 10 which matches the current limit, and it allows increases in increments of 10 up to 100 (effectively unlimited).

The reason I added this is because I was finding that some artwork I was looking for wasn't being scraped. Usually it's a specific official poster or similar, and I had to manually download them and add them that way.

From testing with manually increasing the limit, I didn't encounter any issues, and the other plugins, e.g. TMDB Python TV plugin, doesn't have this kind of limitation and works without issue.

### CODE REVIEW

**Comment by KarellenX** [comment]
>and the other plugins, e.g. TMDB Python TV plugin, doesn't have this kind of limitation and works without issue

Actually it does, and it is a more complex calculation to limit the scraped artwork, to try and find a balance for tv show artwork + season artwork.

Are you aware why this limit was implemented?

**Comment by freakyfr1day** [comment]
> 
> Actually it does, and it is a more complex calculation to limit the scraped artwork, to try and find a balance for tv show artwork + season artwork.

Good to know, I wasn't aware.

> Are you aware why this limit was implemented?

The comment from when the original limit was implemented says it could cause problems in some cases because "a column can be too large for the MySQL integration". I did try to replicate this behavior (I downloaded artwork for movies that had 40-50 posters & Fanart), but couldn't, I'm not a MySQL guy so I've no comment on why that might be.

My thinking was to leave this as an advanced option, people can increase if they think it might be useful, and if they encounter issues it can be dialed back again. I can bump it to expert, and put a 'use at your own risk' type warning on it if you think that might help?

I could also look to try and replicate what was done for the TV plugin if that's considered a better solution? Be aware though, I'm not a coder, my Python is only marginally above novice level at best, and this is the first time I've ever tried to push something to github, so there's a good chance that might be too much for me.

**Comment by KarellenX** [comment]
>Good to know, I wasn't aware.

Here is the calculation... https://github.com/xbmc/metadata.tvshows.themoviedb.org.python/blob/nexus/libs/tmdb.py#L402

> I did try to replicate this behavior (I downloaded artwork for movies that had 40-50 posters & Fanart), but couldn't,

Ok. Try scraping The Simpsons using the TVDB v4 scraper to replicate the problem. 30+ seasons with dozens and dozens of posters per season will kill the scraping quite quickly. TVDB still has an issue with the calculation, and the TVDB developers don't seem to be in a hurry to fix it.

As for your submission, I'll let the developer @rmrector comment whether he wants to implement it.

Thanks for your contribution :)

**Comment by rmrector** [comment]
This option looks good.  Not set to expert, but a note in the label would be good - maybe "Maximum number of each artwork type - many artwork can cause an error scraping to MySQL database". 

Remove the changelog and version update; we'll do that when releasing the next version.

Thanks!

**Comment by freakyfr1day** [comment]
> This option looks good. Not set to expert, but a note in the label would be good - maybe "Maximum number of each artwork type - many artwork can cause an error scraping to MySQL database".
> 
> Remove the changelog and version update; we'll do that when releasing the next version.
> 
> Thanks!

Thanks @rmrector, I think I've done what you've asked, if I've misunderstood, or you want some other changes let me know.

**Pull request merged**
