### PR TITLE
bump to version 0.7.0 - candidate for release

### PR DESCRIPTION
**Pull request by rmrector**
With the other three PRs this will be ready for final evaluation for submitting to the official add-on repo.

### CODE REVIEW

**Comment by Razzeee** [comment]
Have you done a performance comparison with the old scraper? Can you share
that data?

**Comment by rmrector** [comment]
Nothing concrete yet, but clearly slower on Windows. I'll put together a small test case and come up with a better answer soon.

**Comment by rmrector** [comment]
Huh. So the "clearly slower on Windows" had IMDB ratings disabled for the original XML scraper -- with that enabled like the Python scraper the Python scraper is notably faster... on Windows.

Quick time trials on Pi3 and Pi4 do show the expected slowdown, though. The setup is a single movie library with 50 items, scanned into a fresh library with each scraper 5 times, then I compared the average times.

- Pi3 with Kodi 19 LE nightly after Montellese's path settings change
   - Python takes 1.53x time of XML scraper – Python is slower
- Pi4 with Kodi 19 LE 9.2.0 - older, before Montellese's path settings change
   - Python takes 1.42x time of XML scraper – Python is slower
- Windows with Kodi 18 recent HEAD with Montellese's path settings change backport
   - Python takes 0.63x time of XML scraper – Python is faster

Something else is probably up with Windows, the Python scraper shouldn't be faster. Trakt ratings will be responsible for a bit of the slowdown in the Python scraper - I didn't think to disable that for these tests, but I may try on one of the Pis.

**Comment by rmrector** [comment]
Commenting out the trakt ratings didn't significantly improve the Python scraper speed vs the XML.

However considering the speed improvement for the XML scraper when I disable the IMDB rating, it is probably a good idea to put in a switch to disable IMDB rating info for the Python scraper, too. And a switch for trakt since we're there.

**Comment by KarellenX** [comment]
While you are working on ratings... don't suppose you have had a change of mind for RottenTomatoes and Metacritic ratings?

Out of curiosity will you be working on the tvshow version of the scraper?

**Comment by rmrector** [comment]
Not really a change of mind - I'd prefer they go on a more complex scraper like the "Universal" scrapers to keep this one simple and focused, but since such a thing doesn't exist then if someone were to implement a PR for those cleanly (like @Razzeee did for Trakt) I wouldn't be against merging it here for now.

I have no plans for a TV scraper. I'm more interested in getting the above "more complex scraper" implemented for movies so I can see how much of Artwork Beef is still needed.

**Comment by KarellenX** [comment]
ok, thanks

**Pull request merged**
