### PR TITLE
IMDB fix the fix

### PR DESCRIPTION
**Pull request by rmrector**
don't try to convert to float, doesn't parse IMDB pages pre-2021.

### CODE REVIEW

**Comment by KarellenX** [comment]
This fix seems to fix the error when scraping movies that have no ratings at IMDB.

https://www.imdb.com/title/tt8885300/?ref_=nv_sr_srsg_0 scraped ok.

Thanks :)

**Comment by rmrector** [comment]
Thanks for testing.

**Comment by KarellenX** [comment]
Also, what is the trick to downloading a zip file for a single PR like this?
I simply copied the change to my local file. Works ok for one line changes, but not so good for large changes.
Is there an easier way?

**Comment by rmrector** [comment]
Click the "rmrector:imdb-fix-2022-fix" link at the top of this page takes you to the branch, which then has the same "Download as Zip" option as the master branch.

**Comment by KarellenX** [comment]
ah, simple. 
Thanks :)

**Pull request merged**
