### PR TITLE
fix: IMDB rating

### PR DESCRIPTION
**Pull request by rmrector**
Better arrange parsers, rearrange test input to separate files.
Adjust api_utils import to be testable, enable IMDB tests always.
Add 1 end-to-end test for IMDB, not run regularly

### CODE REVIEW

**Comment by KarellenX** [comment]
@rmrector 
I tried downloading the zip file from the Master branch to test this now that it has been merged.
The addon.xml is still using python version 2.26 so it won't install in Kodi v19.

**Comment by rmrector** [comment]
You should just have to change the version in addon.xml.

The release process makes the necessary changes for both Kodi versions.

**Comment by KarellenX** [comment]
Thanks @rmrector 

I tried scraping a number of movies, English and French. Some as follows...

Standard movie... Avengers Endgame - 
No problem

Movie with no IMDB link at TMDB.... https://www.themoviedb.org/movie/847242-explore-a-soviet-dystopia
No problem

Movie with no rating at IMDB... https://www.imdb.com/title/tt8885300/?ref_=nv_sr_srsg_0
Error on line 2263... https://paste.kodi.tv/irazowucap.kodi

**Comment by rmrector** [comment]
Try #142

**Pull request merged**
