### PR TITLE
Fix IMDB ratings and top250

### PR DESCRIPTION
**Pull request by rmrector**
and pull IMDB dealings to a new file.

The last commit removes the unused setting "Add also IMDb ratings". With Kodi's multiple ratings support, IMDB ratings should be added if available anyway.

### CODE REVIEW

**Comment by phate89** [comment]
Not exactly.. IMDb top 250 is gathered from imdb page.. if you skip calling imdb you won't get imdb top 250 position

**Comment by rmrector** [comment]
> IMDb top 250 is gathered from imdb page.. if you skip calling imdb you won't get imdb top 250 position

From my perspective top250 is rating info, too.

What I care about there is a possible configuration that avoids sending a request to IMDB, I just reused the setting with the label that had all the translations.

Looking at it in the morning it is awkward, so I'll rearrange those two settings and labels a bit.

**Comment by phate89** [comment]
Maybe if the goal is avoid to call imdb site is better a separate setting? Themoviedb scraper always gathered imdb top250 position in any case..  if the plan is to fully replace xml scraper this will change behavior once people update to it..

**Comment by rmrector** [comment]
> is better a separate setting? 

That's what I meant.

> in any case.. if the plan is to fully replace xml scraper this will change behavior once people update to it..

Things change in the normal course, but in this case we have a completely new system to work with, so I see no reason things can't change in this transition.

**Pull request merged**
