### PR TITLE
Get Movie form TMDB-ID in filename

### PR DESCRIPTION
**Pull request by Spoon3er**

### CODE REVIEW

**Comment by rmrector** [comment]
Cheers.

However, scrapers don't see the actual filename at all - Kodi sanitizes it to just the necessary search terms first (movie title and year). One particular sanitation rule strips out everything after the year, if found, so this ID won't be in the "title" to match on in many cases anyway. This, as is, will perform inconsistently, and such a feature needs further consideration.

**Comment by Spoon3er** [comment]
You´re right, as I stated at https://forum.kodi.tv/showthread.php?tid=344580&pid=3140168#pid3140168 the pattern for the filename to work must be very precise.
But on the other hand nothing breaks, if the "tmdb"-tag is after the release date. I admit, the search result might differ from expectations due to not parsing the  ID. 
This could be adressed in the readme.md. eg "Filenamepattern to work with tmdb/imdb-ID´s", as this is allready with the manual search (this by the way is, what got me into checking the code)

In my special usercase i didn´t want  to flood my movie library with nfo-files. So the above solution works for me.
Making it persisten for future updates would be great, as the scrapper doesn´t need to be updatet as often and as time flies by I´m sure I wont´t remeber the changes i made.

**Comment by sundermann** [comment]
@rmrector Do you have an opinion on the proposed fix in xbmc/xbmc#23840?

**Comment by rmrector** [comment]
implemented in #205

**Pull request closed without merging**
